from enum import Enum


class Action(str, Enum):
    HOLD = "HOLD"
    ASCEND = "ASCEND"
    DESCEND = "DESCEND"
    ACCELERATE = "ACCELERATE"
    DECELERATE = "DECELERATE"
    TURN_LEFT = "TURN_LEFT"
    TURN_RIGHT = "TURN_RIGHT"
    STABILIZE = "STABILIZE"
    ABORT = "ABORT"


class SystemMode(str, Enum):
    NORMAL = "NORMAL"
    DEGRADED = "DEGRADED"
    SAFE_MODE = "SAFE_MODE"
    FAILED = "FAILED"


class FaultType(str, Enum):
    SENSOR_DRIFT = "SENSOR_DRIFT"
    SENSOR_SPIKE = "SENSOR_SPIKE"
    CONTROLLER_BIAS = "CONTROLLER_BIAS"
    CONTROLLER_TIMEOUT = "CONTROLLER_TIMEOUT"
    DATA_LOSS = "DATA_LOSS"
    SENSOR_NOISE_SPIKE = "SENSOR_NOISE_SPIKE"
    SENSOR_DROPOUT = "SENSOR_DROPOUT"
    CONTROLLER_INVALID_OUTPUT = "CONTROLLER_INVALID_OUTPUT"
    CONTROLLER_LATENCY = "CONTROLLER_LATENCY"
    CONTROLLER_CONFIDENCE_DROP = "CONTROLLER_CONFIDENCE_DROP"
    CONTROLLER_ACTION_BIAS = "CONTROLLER_ACTION_BIAS"
    CONTROLLER_SILENT_FAILURE = "CONTROLLER_SILENT_FAILURE"
    CONFLICTING_CONTROLLER = "CONFLICTING_CONTROLLER"
    COMPOUND_FAULT = "COMPOUND_FAULT"


class HealthStatus(str, Enum):
    HEALTHY = "HEALTHY"
    SUSPECT = "SUSPECT"
    DEGRADED = "DEGRADED"
    CRITICAL = "CRITICAL"
    RECOVERING = "RECOVERING"


class FaultSeverity(str, Enum):
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class SensorStatus(str, Enum):
    OK = "OK"
    DEGRADED = "DEGRADED"
    INVALID = "INVALID"


class VoteOutcome(str, Enum):
    CONSENSUS = "CONSENSUS"
    SPLIT = "SPLIT"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class EventType(str, Enum):
    SENSOR = "SENSOR"
    CONTROLLER = "CONTROLLER"
    VOTE = "VOTE"
    FAULT = "FAULT"
    MODE_CHANGE = "MODE_CHANGE"
    DECISION = "DECISION"
    STATE = "STATE"


class EventSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


CONTROLLER_IDS = ("controller_a", "controller_b", "controller_c")
